frontend/desktop/controllers/WangController.php
<?php

class WangController extends Controller {

	public $layout = 'clean';

	public function actions() {

		return array(

			// captcha action renders the CAPTCHA image displayed on the contact page

			'captcha' => array(

				'class' => 'CCaptchaAction',

				'backColor' => 0xFFFFFF,

			),

			// page action renders "static" pages stored under 'protected/views/site/pages'

			// They can be accessed via: index.php?r=site/page&view=FileName

			'page' => array(

				'class' => 'CViewAction',

			),

		);

	}

	public function actionIndex() {
		$this->layout = "clean";
		$this->render('index');
	}

	public function actionTest() {
		$this->layout = "clean";
		$this->render('test');
	}

	public function actionFramework() {
		$type = Yii::app()->data->getValue("type", "project");
		$this->pageTitle = $type;
		$this->layout = "framework";
		$this->render('framework');
	}

	public function actionError() {
		if ($error = Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest) {
				echo json_encode($error);
			} else {
				$this->layout = "clean";
				$this->render('error', $error);
			}
		}
	}

	public function actionLogin() {
		$this->layout = "clean";
		$this->render('login');
	}

	public function actionLog() {
		$this->layout = "clean";
		$this->render('dailylog');
	}

	public function actionStore() {
		$this->layout = "clean";
		$this->render('storelog');
	}

	public function actionShow() {
		$this->layout = "clean";
		$this->render('showLog');
	}

}

?>

frontend/desktop/views/wang/dailylog.php
<?php

date_default_timezone_set("PRC");
$time = time();
$date = date("Y:m:d 00:00:00", $time);
$time = strtotime($date);
$data = R::getAll('select * from worklog where time > "' . $time . '"');
$on_time = 0;
$off_time = 0;

if (!is_null($data)) {
	if (isset($data[0])) {

		foreach ($data as $key => $value) {
			if ($value['type'] == "on") {
				if ($value['time'] > $on_time) {
					$on_time = $value['time'];
				}
			}

			if ($value['type'] == "off") {
				if ($value['time'] > $off_time) {
					$off_time = $value['time'];
				}
			}
		}
	}
}

?>
<!DOCTYPE html >

<html lang = "en" >

<head >
	<meta charset = "utf-8" / >
	<title >Daily log</title>
	<meta http - equiv = "X-UA-Compatible"
content = "IE=edge" >
	<meta content = "width=device-width, initial-scale=1.0"
name = "viewport" / >
	<meta http - equiv = "Content-type"
content = "text/html; charset=utf-8" >
	<style type="text/css">
	.green.btn {
    color: #FFF;
    background-color: #35AA47;
}

.btn-lg {
    padding: 10px 16px;
    font-size: 18px;
    line-height: 1.33;
    vertical-align: middle;
}

.btn {
    border-width: 0px;
    padding: 7px 14px;
    font-size: 14px;
    outline: medium none !important;
    background-image: none !important;
    filter: none;
    box-shadow: none;
    text-shadow: none;
}

div, input, select, textarea, span, img, table, label, td, th, p, a, button, ul, code, pre, li {
    border-radius: 0px !important;
}

body {
    color: #333;
    font-family: "Open Sans",sans-serif;
    font-size: 13px;
    direction: ltr;
}
	</style>
</head>
<body class = "page-header-fixed page-quick-sidebar-over-content " >

	<div style = "text-align:center; height:100%; margin-top:10%;" >

		<div style = "text-align:center; height:100%; margin-top:10%;" >
			<?php

if ($on_time != 0 && $off_time != 0) {
	$this->
		redirect(array('wang/show'));
} elseif ($on_time == 0) {
	echo '
			<button type = "button"
class = "btn blue btn-lg log" data="on" style="font-size:50px;">签到</button>
			';
} elseif ($off_time == 0) {
	echo '
			<button type = "button"
class = "btn green btn-lg log" data="off" style="font-size:50px;">签退</button>
			';
}
?>
			<input type="hidden" id="request_url" value="<?php echo Yii::app()->assets->getUrlPath("wang/store")?>"></div>

	</div>

	<script type = "text/javascript" >
$(document).ready(function(){
	$(".log").on("click", function() {
		var data = $(this).attr("data");
		var url = $("#request_url").val();
		$.ajax({
				type: "POST",
				url: url,
				data: "type=" + data,
				datatype: "json",

				beforeSend: function() {
				},

				success: function(data) {
					alert(data);
				},

				complete: function(XMLHttpRequest, textStatus) {
				},

				error: function() {
				}
			});
	});
});
	</script>
</body>

</html>

frontend/desktop/views/wang/framework.php
<?php
$type = Yii::app()->data->getValue("type", "project");
echo '<input type="hidden" value="' . $type . '">';

switch ($type) {
case 'project':
	include "subview/project.php";
	break;
case 'gallery':
	include "subview/gallery.php";
	break;
case 'about':
	include "subview/info.php";
	break;
case 'contact':
	include "subview/contact.php";
	break;
default:
	include "subview/empty.php";
	break;
}

?>

frontend/desktop/views/wang/showLog.php
<?php
date_default_timezone_set("PRC");
$time = time();
$date = date("Y:m:d 00:00:00", $time);
$time = strtotime($date);

Yii::app()->
	assets->registerGlobalCss("global/css/components.css");
$data = R::getAll('select * from worklog where time > "' . $time . '"');
$on_time = 0;
$off_time = 0;

if (!is_null($data)) {
	if (isset($data[0])) {

		foreach ($data as $key => $value) {
			if ($value['type'] == "on") {
				if ($value['time'] > $on_time) {
					$on_time = $value['time'];
				}
			}

			if ($value['type'] == "off") {
				if ($value['time'] > $off_time) {
					$off_time = $value['time'];
				}
			}
		}
	}
}
$should_off = $on_time + 25 * 3600;
?>
<div class="portlet blue box" style="width:80%;margin-left:10%;margin-top:5%;">
	<div class="portlet-title">
		<div class="caption"> <i class="fa fa-cogs"></i>
			今日签到
		</div>
	</div>
	<div class="portlet-body">
		<h4 class="block">
			<?php
if ($on_time == 0) {
	echo "尚未签到";
} else {
	echo date('Y/m/d H:i:s', $on_time);
	echo '<input type="hidden" id="off_time" value="' . $should_off . '">';
}
?></h4>
	</div>
</div>

<div class="portlet green box" style="width:80%;margin-left:10%;margin-top:5%;">
	<div class="portlet-title">
		<div class="caption"> <i class="fa fa-cogs"></i>
			今日签退
		</div>
	</div>
	<div class="portlet-body">
		<h4 class="block">
			<?php
if ($off_time == 0) {
	echo "尚未签退";
} else {
	echo date('Y/m/d H:i:s', $off_time);
}
?></h4>
	</div>
</div>

<div class="portlet red box" style="width:80%;margin-left:10%;margin-top:5%;">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-cogs"></i>
			下班时间
		</div>
	</div>
	<div class="portlet-body">
		 <?php
if ($off_time == 0 && $on_time != 0 && time() < $on_time + 9 * 3600) {
	$remain = $should_off - time();
	echo '<input id="count" type="hidden" value="' . $remain . '"><h4 class="block" id="clock"></h4>';
} elseif ($on_time == 0) {
	echo '<h4 class="block" id="clock">尚未开始。</h4>';
} else {
	echo '<h4 class="block" id="clock">已下班。</h4>';

}
?>
	</div>
</div>

<script type="text/javascript">

var count_id = 0;

function count(){
	var data = $("#count").val();
	if(data <= 16*3600 || isNaN(data))
	{
		data = "已下班";
		clearInterval(count_id);
	}else{
		data--;
		var newDate = new Date();
		newDate.setTime(data * 1000);
		show = newDate.format('h:m:s');
	}
	$("#clock").html(show);
	$("#count").val(data);
}

$(function(){
	if($("#count").length >0)
	{
		count_id = setInterval(count, 1000);
	}
});

Date.prototype.format = function(format) {
       var date = {
              "M+": this.getMonth() + 1,
              "d+": this.getDate(),
              "h+": this.getHours(),
              "m+": this.getMinutes(),
              "s+": this.getSeconds(),
              "q+": Math.floor((this.getMonth() + 3) / 3),
              "S+": this.getMilliseconds()
       };
       if (/(y+)/i.test(format)) {
              format = format.replace(RegExp.$1, (this.getFullYear() + '').substr(4 - RegExp.$1.length));
       }
       for (var k in date) {
              if (new RegExp("(" + k + ")").test(format)) {
                     format = format.replace(RegExp.$1, RegExp.$1.length == 1
                            ? date[k] : ("00" + date[k]).substr(("" + date[k]).length));
              }
       }
       return format;
}

</script>

frontend/desktop/views/wang/storelog.php
<?php
$type = Yii::app()->data->getValue('type');
$item = R::dispense("worklog");
$item->time = time();
$item->type = $type;
$id = R::store($item);
echo "签到成功";
?>